#!/bin/env python
import os
import json

VERIFY=True

structure = {}
for root, dirs, files in os.walk('.'):
    if root == os.path.curdir:
        continue
    lang = root.split('/')[-1]
    cur = structure[lang] = {}
    for fname in files:
        if not fname.endswith('.json'):
            continue
        translations = json.load(open(os.path.join(root, fname)))
        if VERIFY:
            for k, v in translations.items():
                if k in cur:
                    print(f"ERROR: {k} already defined for {lang}, found in {fname}")
        cur.update(translations)

output = open('../front/js/locales.js', 'w')
output.write("const locales = ")
json.dump(structure, output)
